[package]
name = "franz"
version = "0.1.0"
authors = ["Kabir Samsi <samsikabir@gmail.com>"]
edition = "2021"

[build-dependencies]
lalrpop = "0.20.2"

[dependencies]
lalrpop-util = { version = "0.20.2", features = ["lexer", "unicode"] }
match_deref = "0.1.1"

[dev-dependencies]
insta = "1.39.0"
